"""Build the hospital database in memory and run every query in sql/queries.sql.

    python run_queries.py            # print every query with its result
    python run_queries.py 24 25      # only queries 24 and 25
    python run_queries.py --save     # also write output/results.md

Only the standard library is needed (sqlite3).
"""

import os
import re
import sqlite3
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SQL = os.path.join(ROOT, "sql")


def build_database():
    """Create an in-memory database from schema.sql and data.sql."""
    con = sqlite3.connect(":memory:")
    con.execute("PRAGMA foreign_keys = ON")  # SQLite ignores foreign keys unless asked
    for name in ("schema.sql", "data.sql"):
        with open(os.path.join(SQL, name), encoding="utf-8") as f:
            con.executescript(f.read())
    bad = con.execute("PRAGMA foreign_key_check").fetchall()
    if bad:
        raise RuntimeError(f"foreign key problems after loading: {bad}")
    return con


def load_queries(path=None):
    """Split queries.sql into {number: (title, sql)} using the '-- Q<n>: title' lines."""
    path = path or os.path.join(SQL, "queries.sql")
    with open(path, encoding="utf-8") as f:
        text = f.read()
    queries = {}
    parts = re.split(r"^-- Q(\d+): (.*)$", text, flags=re.M)
    # parts = [preamble, num, title, body, num, title, body, ...]
    for i in range(1, len(parts), 3):
        number, title, body = int(parts[i]), parts[i + 1].strip(), parts[i + 2]
        statement = "\n".join(
            line for line in body.splitlines() if not line.strip().startswith("--")
        ).strip()
        queries[number] = (title, statement)
    return queries


def run(con, sql):
    cur = con.execute(sql)
    return [d[0] for d in cur.description], cur.fetchall()


def as_table(columns, rows):
    cells = [columns] + [[("" if v is None else str(v)) for v in r] for r in rows]
    widths = [max(len(row[i]) for row in cells) for i in range(len(columns))]
    line = lambda row: "| " + " | ".join(c.ljust(w) for c, w in zip(row, widths)) + " |"
    rule = "|-" + "-|-".join("-" * w for w in widths) + "-|"
    return "\n".join([line(cells[0]), rule] + [line(r) for r in cells[1:]])


def main(argv):
    save = "--save" in argv
    wanted = {int(a) for a in argv if a.isdigit()}
    con = build_database()
    queries = load_queries()
    report = ["# Query results", "", "Generated by `python run_queries.py --save`.", ""]
    for number, (title, sql) in sorted(queries.items()):
        if wanted and number not in wanted:
            continue
        columns, rows = run(con, sql)
        table = as_table(columns, rows) if rows else "(no rows)"
        print(f"\nQ{number}: {title}  [{len(rows)} rows]\n{table}")
        report += [f"## Q{number}: {title}", "", f"{len(rows)} rows", "", table, ""]
    if save:
        os.makedirs(os.path.join(ROOT, "output"), exist_ok=True)
        with open(os.path.join(ROOT, "output", "results.md"), "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(report))
        print("\nsaved output/results.md")


if __name__ == "__main__":
    main(sys.argv[1:])
